#ifndef __XML_GENERATED_DEPLOYMENT_H_
#define __XML_GENERATED_DEPLOYMENT_H_

#define POK_GENERATED_CODE	1

#define POK_NEEDS_LIBC_STDIO	1

#define POK_CONFIG_NB_THREADS	5

#define POK_NEEDS_ARINC653_PROCESS	1

#define POK_NEEDS_ARINC653_PARTITION	1

#define POK_NEEDS_ARINC653_TIME	1

#define POK_NEEDS_ARINC653	1

#define POK_NEEDS_ARINC653_QUEUEING	1

#define POK_NEEDS_ARINC653_SAMPLING	1

#define POK_CONFIG_MAX_MESSAGE_SIZE	256

#define POK_CONFIG_PART_NB_INPUT_QUEUING_PORTS	1

#define POK_CONFIG_PART_NB_INPUT_SAMPLING_PORTS	1

#define POK_CONFIG_PART_MAX_QUEUING_MESSAGES	2

#define POK_CONFIG_NB_SYSTEM_PORTS	8

#endif